let num1: number = 10;
let num2: number = 20;
let num3: number;
num3= num1+num2;
console.log("addition of 2 number" + num3);
num3 = num1-num2;
console.log("sub of 2 number" + num3);
num3 = num1*num2;
console.log("multiply of 2 number" + num3);
num3 = num1/num2;
console.log("division of 2 number" + num3);